// <auto-generated />
using System;
using FoodMap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodMap.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260924173930_CapNhatThuocTinhNCC")]
    partial class CapNhatThuocTinhNCC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodMap.Models.Chude", b =>
                {
                    b.Property<int>("MaCd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCd"));

                    b.Property<int>("MaDm")
                        .HasColumnType("int");

                    b.Property<string>("TenCd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCd");

                    b.HasIndex("MaDm");

                    b.ToTable("Chude");
                });

            modelBuilder.Entity("FoodMap.Models.Cthoadon", b =>
                {
                    b.Property<int>("MaCthd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCthd"));

                    b.Property<int?>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("MaHd")
                        .HasColumnType("int");

                    b.Property<int>("MaMh")
                        .HasColumnType("int");

                    b.Property<string>("MaVoucher")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("SoLuong")
                        .HasColumnType("smallint");

                    b.Property<int?>("ThanhTien")
                        .HasColumnType("int");

                    b.HasKey("MaCthd");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaMh");

                    b.ToTable("Cthoadon");
                });

            modelBuilder.Entity("FoodMap.Models.Danhmuc", b =>
                {
                    b.Property<int>("MaDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDm"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDm");

                    b.ToTable("Danhmuc");
                });

            modelBuilder.Entity("FoodMap.Models.Hoadon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<int>("MaKh")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TongTien")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHd");

                    b.HasIndex("MaKh");

                    b.ToTable("Hoadon");
                });

            modelBuilder.Entity("FoodMap.Models.Khachhang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaKh");

                    b.ToTable("Khachhang");
                });

            modelBuilder.Entity("FoodMap.Models.Mathang", b =>
                {
                    b.Property<int>("MaMh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMh"));

                    b.Property<int?>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int?>("GiaGoc")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaCd")
                        .HasColumnType("int");

                    b.Property<int>("MaNcc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("SoLuong")
                        .HasColumnType("smallint");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMh");

                    b.HasIndex("MaCd");

                    b.HasIndex("MaNcc");

                    b.ToTable("Mathang");
                });

            modelBuilder.Entity("FoodMap.Models.Nhacungcap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNcc"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("TrangThaiXacThuc")
                        .HasColumnType("int");

                    b.HasKey("MaNcc");

                    b.ToTable("Nhacungcap");
                });

            modelBuilder.Entity("FoodMap.Models.Chude", b =>
                {
                    b.HasOne("FoodMap.Models.Danhmuc", "Danhmuc")
                        .WithMany("Chudes")
                        .HasForeignKey("MaDm")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Danhmuc");
                });

            modelBuilder.Entity("FoodMap.Models.Cthoadon", b =>
                {
                    b.HasOne("FoodMap.Models.Hoadon", "Hoadon")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaHd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodMap.Models.Mathang", "Mathang")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaMh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hoadon");

                    b.Navigation("Mathang");
                });

            modelBuilder.Entity("FoodMap.Models.Hoadon", b =>
                {
                    b.HasOne("FoodMap.Models.Khachhang", "Khachhang")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachhang");
                });

            modelBuilder.Entity("FoodMap.Models.Mathang", b =>
                {
                    b.HasOne("FoodMap.Models.Chude", "Chude")
                        .WithMany("Mathangs")
                        .HasForeignKey("MaCd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodMap.Models.Nhacungcap", "Nhacungcap")
                        .WithMany("Mathangs")
                        .HasForeignKey("MaNcc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chude");

                    b.Navigation("Nhacungcap");
                });

            modelBuilder.Entity("FoodMap.Models.Chude", b =>
                {
                    b.Navigation("Mathangs");
                });

            modelBuilder.Entity("FoodMap.Models.Danhmuc", b =>
                {
                    b.Navigation("Chudes");
                });

            modelBuilder.Entity("FoodMap.Models.Hoadon", b =>
                {
                    b.Navigation("Cthoadons");
                });

            modelBuilder.Entity("FoodMap.Models.Khachhang", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("FoodMap.Models.Mathang", b =>
                {
                    b.Navigation("Cthoadons");
                });

            modelBuilder.Entity("FoodMap.Models.Nhacungcap", b =>
                {
                    b.Navigation("Mathangs");
                });
#pragma warning restore 612, 618
        }
    }
}
